name: Checkmarx One Scan
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          project_name: github.action-alonso
          cx_tenant: cx_seg
          base_uri: https://eu.ast.checkmarx.net/
          cx_client_id: alonso-github
          cx_client_secret: T484ksGlI5WreT97feK81kqkQJzpCQBs
          additional_params: --debug --scan-types sast,sca --file-filter !containers-resolution.json
